<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.dagere</groupId>
     <artifactId>nodeDiffDetector-parent</artifactId>
     <version>0.0.3-SNAPSHOT</version>
     <name>nodeDiffDetector-parent</name>
	<packaging>pom</packaging>

	<description>Detects the difference between two commits of a software by parsing the code</description>
     <url>https://github.com/DaGeRe/nodeDiffDetector/</url>

	<properties>
		<additionalparam>-Xdoclint:none</additionalparam>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>
	
	<build>
	  <plugins>
		  <plugin>
		     <groupId>org.apache.maven.plugins</groupId>
		     <artifactId>maven-deploy-plugin</artifactId>
		     <version>3.1.4</version>
		     <configuration>
		       <skip>true</skip>
		     </configuration>
		   </plugin>
	   </plugins>
	</build>


	<modules>
		<module>nodeDiffDetector-library</module>
	</modules>
	
	<profiles>
		<profile>
			<id>buildStarter</id>
			<modules>
				<module>nodeDiffDetector-library</module>
				<module>nodeDiffDetector-starter</module>
			</modules>
		</profile>
	</profiles>

	<licenses>
		<license>
			<name>Apache License</name>
			<url>https://www.apache.org/licenses/LICENSE-2.0</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>DaGeRe</id>
			<name>David Georg Reichelt</name>
			<email>kopeme@dagere.de</email>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:ssh://github.com:DaGeRe/kieker-source-instrumentation-dagere.git</connection>
		<developerConnection>scm:git:git@github.com:DaGeRe/kieker-source-instrumentation-dagere.git</developerConnection>
		<url>https://git@github.com:DaGeRe/kieker-source-instrumentation-dagere.git</url>
		<tag>HEAD</tag>
	</scm>
</project>

